// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository.Database;

namespace Repository.Migrations
{
    [DbContext(typeof(dbContext))]
    [Migration("20210325141218_修改会员信息表")]
    partial class 修改会员信息表
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Repository.Database.TAlipayKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AesKey")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("aeskey");

                    b.Property<string>("AlipayPublicKey")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("alipaypublickey");

                    b.Property<string>("AppId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("appid");

                    b.Property<string>("AppPrivateKey")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("appprivatekey");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("createtime");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("deletetime");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isdelete");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("remarks");

                    b.Property<int>("Sort")
                        .HasColumnType("int")
                        .HasColumnName("sort");

                    b.HasKey("Id");

                    b.ToTable("t_alipaykey");
                });

            modelBuilder.Entity("Repository.Database.TArticle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Abstract")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("abstract");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("categoryid");

                    b.Property<int>("ClickCount")
                        .HasColumnType("int")
                        .HasColumnName("clickcount");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("createtime");

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("createuserid");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("deletetime");

                    b.Property<Guid?>("DeleteUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("deleteuserid");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isdelete");

                    b.Property<bool>("IsDisplay")
                        .HasColumnType("bit")
                        .HasColumnName("isdisplay");

                    b.Property<bool>("IsRecommend")
                        .HasColumnType("bit")
                        .HasColumnName("isrecommend");

                    b.Property<int>("Sort")
                        .HasColumnType("int")
                        .HasColumnName("sort");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("DeleteUserId");

                    b.ToTable("t_article");
                });

            modelBuilder.Entity("Repository.Database.TCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("channelid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("createtime");

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("createuserid");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("deletetime");

                    b.Property<Guid?>("DeleteUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("deleteuserid");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isdelete");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("parentid");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("remarks");

                    b.Property<int>("Sort")
                        .HasColumnType("int")
                        .HasColumnName("sort");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("DeleteUserId");

                    b.HasIndex("ParentId");

                    b.ToTable("t_category");
                });

            modelBuilder.Entity("Repository.Database.TChannel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("createtime");

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("createuserid");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("deletetime");

                    b.Property<Guid?>("DeleteUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("deleteuserid");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isdelete");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("remarks");

                    b.Property<int>("Sort")
                        .HasColumnType("int")
                        .HasColumnName("sort");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("DeleteUserId");

                    b.ToTable("t_channel");
                });

            modelBuilder.Entity("Repository.Database.TCount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("Count")
                        .HasColumnType("int")
                        .HasColumnName("count");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("createtime");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("deletetime");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isdelete");

                    b.Property<string>("Tag")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tag");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatetime");

                    b.HasKey("Id");

                    b.ToTable("t_count");
                });

            modelBuilder.Entity("Repository.Database.TCoursePackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("createtime");

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("createuserid");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("deletetime");

                    b.Property<Guid?>("DeleteUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("deleteuserid");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isdelete");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatetime");

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("updateuserid");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("DeleteUserId");

                    b.HasIndex("UpdateUserId");

                    b.ToTable("t_coursepackage");
                });

            modelBuilder.Entity("Repository.Database.TDictionary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("createtime");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("deletetime");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isdelete");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("key");

                    b.Property<int>("Sort")
                        .HasColumnType("int")
                        .HasColumnName("sort");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.ToTable("t_dictionary");
                });

            modelBuilder.Entity("Repository.Database.TFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("createtime");

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("createuserid");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("deletetime");

                    b.Property<Guid?>("DeleteUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("deleteuserid");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isdelete");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("path");

                    b.Property<string>("Sign")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sign");

                    b.Property<int>("Sort")
                        .HasColumnType("int")
                        .HasColumnName("sort");

                    b.Property<string>("Table")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("table");

                    b.Property<Guid>("TableId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tableid");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("DeleteUserId");

                    b.HasIndex("TableId");

                    b.ToTable("t_file");
                });

            modelBuilder.Entity("Repository.Database.TFileGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("createtime");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("deletetime");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fileid");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isdelete");

                    b.Property<bool>("Isfull")
                        .HasColumnType("bit")
                        .HasColumnName("isfull");

                    b.Property<bool>("Issynthesis")
                        .HasColumnType("bit")
                        .HasColumnName("issynthesis");

                    b.Property<int>("Slicing")
                        .HasColumnType("int")
                        .HasColumnName("slicing");

                    b.Property<string>("Unique")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("unique");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatetime");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.ToTable("t_filegroup");
                });

            modelBuilder.Entity("Repository.Database.TFileGroupFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("createtime");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("deletetime");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fileid");

                    b.Property<int>("Index")
                        .HasColumnType("int")
                        .HasColumnName("index");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isdelete");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("path");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.ToTable("t_filegroupfile");
                });

            modelBuilder.Entity("Repository.Database.TGuidToInt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("guid");

                    b.HasKey("Id");

                    b.ToTable("t_guidtoint");
                });

            modelBuilder.Entity("Repository.Database.TImgBaiduAI", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("createtime");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("deletetime");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fileid");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isdelete");

                    b.Property<string>("Result")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("result");

                    b.Property<string>("Unique")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("unique");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatetime");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.ToTable("t_imgbaiduai");
                });

            modelBuilder.Entity("Repository.Database.TLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("createtime");

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("createuserid");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("deletetime");

                    b.Property<Guid?>("DeleteUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("deleteuserid");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isdelete");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("remarks");

                    b.Property<int>("Sort")
                        .HasColumnType("int")
                        .HasColumnName("sort");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("DeleteUserId");

                    b.ToTable("t_link");
                });

            modelBuilder.Entity("Repository.Database.TLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("createtime");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("deletetime");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isdelete");

                    b.Property<string>("Sign")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sign");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("t_log");
                });

            modelBuilder.Entity("Repository.Database.TMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ChildName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("childname");

                    b.Property<string>("Class")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("class");

                    b.Property<int>("CourseCount")
                        .HasColumnType("int")
                        .HasColumnName("coursecount");

                    b.Property<Guid?>("CoursePackageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("coursepackageid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("createtime");

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("createuserid");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("deletetime");

                    b.Property<Guid?>("DeleteUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("deleteuserid");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isdelete");

                    b.Property<string>("ParentName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("parentname");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phonenumber");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("remarks");

                    b.Property<string>("SchoolName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("schoolname");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatetime");

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("updateuserid");

                    b.HasKey("Id");

                    b.HasIndex("CoursePackageId");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("DeleteUserId");

                    b.HasIndex("UpdateUserId");

                    b.ToTable("t_member");
                });

            modelBuilder.Entity("Repository.Database.TMemberWxPhone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("createtime");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("deletetime");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isdelete");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phonenumber");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatetime");

                    b.Property<string>("WeixinCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("weixincode");

                    b.HasKey("Id");

                    b.ToTable("t_memberwxphone");
                });

            modelBuilder.Entity("Repository.Database.TMemberWxPhoneMessgeLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("createtime");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("deletetime");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isdelete");

                    b.Property<string>("TMemberWxPhoneId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tmemberwxphoneid");

                    b.Property<Guid?>("TMember_Wx_PhoneId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tmember_wx_phoneid");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatetime");

                    b.HasKey("Id");

                    b.HasIndex("TMember_Wx_PhoneId");

                    b.ToTable("t_memberwxphonemessgelog");
                });

            modelBuilder.Entity("Repository.Database.TOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("createtime");

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("createuserid");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("deletetime");

                    b.Property<Guid?>("DeleteUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("deleteuserid");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isdelete");

                    b.Property<string>("OrderNo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("orderno");

                    b.Property<string>("PayType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("paytype");

                    b.Property<decimal?>("Payprice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("payprice");

                    b.Property<bool>("Paystate")
                        .HasColumnType("bit")
                        .HasColumnName("paystate");

                    b.Property<DateTime?>("Paytime")
                        .HasColumnType("datetime2")
                        .HasColumnName("paytime");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(38,2)")
                        .HasColumnName("price");

                    b.Property<string>("SerialNo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("serialno");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("state");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatetime");

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("updateuserid");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("DeleteUserId");

                    b.HasIndex("UpdateUserId");

                    b.ToTable("t_order");
                });

            modelBuilder.Entity("Repository.Database.TOrderDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("createtime");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("deletetime");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isdelete");

                    b.Property<int>("Number")
                        .HasColumnType("int")
                        .HasColumnName("number");

                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("orderid");

                    b.Property<Guid?>("OrderId1")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("orderid1");

                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("productid");

                    b.HasKey("Id");

                    b.HasIndex("OrderId1");

                    b.ToTable("t_orderdetail");
                });

            modelBuilder.Entity("Repository.Database.TProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("createtime");

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("createuserid");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("deletetime");

                    b.Property<Guid?>("DeleteUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("deleteuserid");

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("detail");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isdelete");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(38,2)")
                        .HasColumnName("price");

                    b.Property<string>("SKU")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sku");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatetime");

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("updateuserid");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("DeleteUserId");

                    b.HasIndex("UpdateUserId");

                    b.ToTable("t_product");
                });

            modelBuilder.Entity("Repository.Database.TRegionArea", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Area")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("area");

                    b.Property<int>("CityId")
                        .HasColumnType("int")
                        .HasColumnName("cityid");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("t_regionarea");
                });

            modelBuilder.Entity("Repository.Database.TRegionCity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("city");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int")
                        .HasColumnName("provinceid");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("t_regioncity");
                });

            modelBuilder.Entity("Repository.Database.TRegionProvince", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("province");

                    b.HasKey("Id");

                    b.ToTable("t_regionprovince");
                });

            modelBuilder.Entity("Repository.Database.TRegionTown", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("AreaId")
                        .HasColumnType("int")
                        .HasColumnName("areaid");

                    b.Property<string>("Town")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("town");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.ToTable("t_regiontown");
                });

            modelBuilder.Entity("Repository.Database.TRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("createtime");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("deletetime");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isdelete");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("remarks");

                    b.HasKey("Id");

                    b.ToTable("t_role");
                });

            modelBuilder.Entity("Repository.Database.TSign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("createtime");

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("createuserid");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("deletetime");

                    b.Property<Guid?>("DeleteUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("deleteuserid");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isdelete");

                    b.Property<string>("Sign")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sign");

                    b.Property<string>("Table")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("table");

                    b.Property<Guid>("TableId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tableid");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("DeleteUserId");

                    b.HasIndex("TableId");

                    b.ToTable("t_sign");
                });

            modelBuilder.Entity("Repository.Database.TUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("createtime");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("deletetime");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isdelete");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("NickName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nickname");

                    b.Property<string>("PassWord")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("roleid");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatetime");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("t_user");
                });

            modelBuilder.Entity("Repository.Database.TUserBindAlipay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("AlipayKeyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("alipaykeyid");

                    b.Property<string>("AlipayUserId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("alipayuserid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("createtime");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("deletetime");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isdelete");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("userid");

                    b.HasKey("Id");

                    b.HasIndex("AlipayKeyId");

                    b.HasIndex("UserId");

                    b.ToTable("t_userbindalipay");
                });

            modelBuilder.Entity("Repository.Database.TUserBindWeixin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("createtime");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("deletetime");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isdelete");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("userid");

                    b.Property<Guid>("WeiXinKeyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("weixinkeyid");

                    b.Property<string>("WeiXinOpenId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("weixinopenid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WeiXinKeyId");

                    b.ToTable("t_userbindweixin");
                });

            modelBuilder.Entity("Repository.Database.TUserInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("company");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("createtime");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("deletetime");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isdelete");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("position");

                    b.Property<string>("QQ")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("qq");

                    b.Property<int>("RegionAreaId")
                        .HasColumnType("int")
                        .HasColumnName("regionareaid");

                    b.Property<bool?>("Sex")
                        .HasColumnType("bit")
                        .HasColumnName("sex");

                    b.Property<string>("Signature")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("signature");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("userid");

                    b.Property<string>("WeChat")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("wechat");

                    b.HasKey("Id");

                    b.HasIndex("RegionAreaId");

                    b.HasIndex("UserId");

                    b.ToTable("t_userinfo");
                });

            modelBuilder.Entity("Repository.Database.TUserToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("createtime");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("deletetime");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isdelete");

                    b.Property<Guid>("LastId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("lastid");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("userid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("t_usertoken");
                });

            modelBuilder.Entity("Repository.Database.TWeChatNoPublicTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("createtime");

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("createuserid");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("deletetime");

                    b.Property<Guid?>("DeleteUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("deleteuserid");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isdelete");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatetime");

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("updateuserid");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("DeleteUserId");

                    b.HasIndex("UpdateUserId");

                    b.ToTable("t_wechatnopublictemplate");
                });

            modelBuilder.Entity("Repository.Database.TWebInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("FootCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("footcode");

                    b.Property<string>("ManagerAddress")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("manageraddress");

                    b.Property<string>("ManagerEmail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("manageremail");

                    b.Property<string>("ManagerName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("managername");

                    b.Property<string>("ManagerPhone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("managerphone");

                    b.Property<string>("RecordNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("recordnumber");

                    b.Property<string>("SeoDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("seodescription");

                    b.Property<string>("SeoKeyWords")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("seokeywords");

                    b.Property<string>("SeoTitle")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("seotitle");

                    b.Property<string>("WebUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("weburl");

                    b.HasKey("Id");

                    b.ToTable("t_webinfo");
                });

            modelBuilder.Entity("Repository.Database.TWeiXinKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("createtime");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("deletetime");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isdelete");

                    b.Property<string>("MchId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mchid");

                    b.Property<string>("MchKey")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mchkey");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("remarks");

                    b.Property<int>("Sort")
                        .HasColumnType("int")
                        .HasColumnName("sort");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type");

                    b.Property<string>("WxAppId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("wxappid");

                    b.Property<string>("WxAppSecret")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("wxappsecret");

                    b.HasKey("Id");

                    b.ToTable("t_weixinkey");
                });

            modelBuilder.Entity("Repository.Database.TArticle", b =>
                {
                    b.HasOne("Repository.Database.TCategory", "Category")
                        .WithMany("TArticle")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Database.TUser", "CreateUser")
                        .WithMany()
                        .HasForeignKey("CreateUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Database.TUser", "DeleteUser")
                        .WithMany()
                        .HasForeignKey("DeleteUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");

                    b.Navigation("CreateUser");

                    b.Navigation("DeleteUser");
                });

            modelBuilder.Entity("Repository.Database.TCategory", b =>
                {
                    b.HasOne("Repository.Database.TChannel", "Channel")
                        .WithMany("TCategory")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Database.TUser", "CreateUser")
                        .WithMany()
                        .HasForeignKey("CreateUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Database.TUser", "DeleteUser")
                        .WithMany()
                        .HasForeignKey("DeleteUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Repository.Database.TCategory", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Channel");

                    b.Navigation("CreateUser");

                    b.Navigation("DeleteUser");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Repository.Database.TChannel", b =>
                {
                    b.HasOne("Repository.Database.TUser", "CreateUser")
                        .WithMany()
                        .HasForeignKey("CreateUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Database.TUser", "DeleteUser")
                        .WithMany()
                        .HasForeignKey("DeleteUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreateUser");

                    b.Navigation("DeleteUser");
                });

            modelBuilder.Entity("Repository.Database.TCoursePackage", b =>
                {
                    b.HasOne("Repository.Database.TUser", "CreateUser")
                        .WithMany()
                        .HasForeignKey("CreateUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Database.TUser", "DeleteUser")
                        .WithMany()
                        .HasForeignKey("DeleteUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Repository.Database.TUser", "UpdateUser")
                        .WithMany()
                        .HasForeignKey("UpdateUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreateUser");

                    b.Navigation("DeleteUser");

                    b.Navigation("UpdateUser");
                });

            modelBuilder.Entity("Repository.Database.TFile", b =>
                {
                    b.HasOne("Repository.Database.TUser", "CreateUser")
                        .WithMany()
                        .HasForeignKey("CreateUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Database.TUser", "DeleteUser")
                        .WithMany()
                        .HasForeignKey("DeleteUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreateUser");

                    b.Navigation("DeleteUser");
                });

            modelBuilder.Entity("Repository.Database.TFileGroup", b =>
                {
                    b.HasOne("Repository.Database.TFile", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("Repository.Database.TFileGroupFile", b =>
                {
                    b.HasOne("Repository.Database.TFile", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("Repository.Database.TImgBaiduAI", b =>
                {
                    b.HasOne("Repository.Database.TFile", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("Repository.Database.TLink", b =>
                {
                    b.HasOne("Repository.Database.TUser", "CreateUser")
                        .WithMany()
                        .HasForeignKey("CreateUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Database.TUser", "DeleteUser")
                        .WithMany()
                        .HasForeignKey("DeleteUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreateUser");

                    b.Navigation("DeleteUser");
                });

            modelBuilder.Entity("Repository.Database.TMember", b =>
                {
                    b.HasOne("Repository.Database.TCoursePackage", "CoursePackage")
                        .WithMany()
                        .HasForeignKey("CoursePackageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Repository.Database.TUser", "CreateUser")
                        .WithMany()
                        .HasForeignKey("CreateUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Database.TUser", "DeleteUser")
                        .WithMany()
                        .HasForeignKey("DeleteUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Repository.Database.TUser", "UpdateUser")
                        .WithMany()
                        .HasForeignKey("UpdateUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CoursePackage");

                    b.Navigation("CreateUser");

                    b.Navigation("DeleteUser");

                    b.Navigation("UpdateUser");
                });

            modelBuilder.Entity("Repository.Database.TMemberWxPhoneMessgeLog", b =>
                {
                    b.HasOne("Repository.Database.TMemberWxPhone", "TMember_Wx_Phone")
                        .WithMany()
                        .HasForeignKey("TMember_Wx_PhoneId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TMember_Wx_Phone");
                });

            modelBuilder.Entity("Repository.Database.TOrder", b =>
                {
                    b.HasOne("Repository.Database.TUser", "CreateUser")
                        .WithMany("TOrder")
                        .HasForeignKey("CreateUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Database.TUser", "DeleteUser")
                        .WithMany()
                        .HasForeignKey("DeleteUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Repository.Database.TUser", "UpdateUser")
                        .WithMany()
                        .HasForeignKey("UpdateUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreateUser");

                    b.Navigation("DeleteUser");

                    b.Navigation("UpdateUser");
                });

            modelBuilder.Entity("Repository.Database.TOrderDetail", b =>
                {
                    b.HasOne("Repository.Database.TOrder", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId1")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Repository.Database.TProduct", b =>
                {
                    b.HasOne("Repository.Database.TUser", "CreateUser")
                        .WithMany()
                        .HasForeignKey("CreateUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Database.TUser", "DeleteUser")
                        .WithMany()
                        .HasForeignKey("DeleteUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Repository.Database.TUser", "UpdateUser")
                        .WithMany()
                        .HasForeignKey("UpdateUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreateUser");

                    b.Navigation("DeleteUser");

                    b.Navigation("UpdateUser");
                });

            modelBuilder.Entity("Repository.Database.TRegionArea", b =>
                {
                    b.HasOne("Repository.Database.TRegionCity", "City")
                        .WithMany("TRegionArea")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Repository.Database.TRegionCity", b =>
                {
                    b.HasOne("Repository.Database.TRegionProvince", "Province")
                        .WithMany("TRegionCity")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("Repository.Database.TRegionTown", b =>
                {
                    b.HasOne("Repository.Database.TRegionArea", "Area")
                        .WithMany("TRegionTown")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("Repository.Database.TSign", b =>
                {
                    b.HasOne("Repository.Database.TUser", "CreateUser")
                        .WithMany()
                        .HasForeignKey("CreateUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Database.TUser", "DeleteUser")
                        .WithMany()
                        .HasForeignKey("DeleteUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreateUser");

                    b.Navigation("DeleteUser");
                });

            modelBuilder.Entity("Repository.Database.TUser", b =>
                {
                    b.HasOne("Repository.Database.TRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Repository.Database.TUserBindAlipay", b =>
                {
                    b.HasOne("Repository.Database.TAlipayKey", "AlipayKey")
                        .WithMany()
                        .HasForeignKey("AlipayKeyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Database.TUser", "User")
                        .WithMany("TUserBindAlipay")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AlipayKey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repository.Database.TUserBindWeixin", b =>
                {
                    b.HasOne("Repository.Database.TUser", "User")
                        .WithMany("TUserBindWeixin")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Database.TWeiXinKey", "WeiXinKey")
                        .WithMany()
                        .HasForeignKey("WeiXinKeyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("WeiXinKey");
                });

            modelBuilder.Entity("Repository.Database.TUserInfo", b =>
                {
                    b.HasOne("Repository.Database.TRegionArea", "RegionArea")
                        .WithMany()
                        .HasForeignKey("RegionAreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Database.TUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RegionArea");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repository.Database.TUserToken", b =>
                {
                    b.HasOne("Repository.Database.TUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repository.Database.TWeChatNoPublicTemplate", b =>
                {
                    b.HasOne("Repository.Database.TUser", "CreateUser")
                        .WithMany()
                        .HasForeignKey("CreateUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Database.TUser", "DeleteUser")
                        .WithMany()
                        .HasForeignKey("DeleteUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Repository.Database.TUser", "UpdateUser")
                        .WithMany()
                        .HasForeignKey("UpdateUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreateUser");

                    b.Navigation("DeleteUser");

                    b.Navigation("UpdateUser");
                });

            modelBuilder.Entity("Repository.Database.TCategory", b =>
                {
                    b.Navigation("TArticle");
                });

            modelBuilder.Entity("Repository.Database.TChannel", b =>
                {
                    b.Navigation("TCategory");
                });

            modelBuilder.Entity("Repository.Database.TOrder", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("Repository.Database.TRegionArea", b =>
                {
                    b.Navigation("TRegionTown");
                });

            modelBuilder.Entity("Repository.Database.TRegionCity", b =>
                {
                    b.Navigation("TRegionArea");
                });

            modelBuilder.Entity("Repository.Database.TRegionProvince", b =>
                {
                    b.Navigation("TRegionCity");
                });

            modelBuilder.Entity("Repository.Database.TUser", b =>
                {
                    b.Navigation("TOrder");

                    b.Navigation("TUserBindAlipay");

                    b.Navigation("TUserBindWeixin");
                });
#pragma warning restore 612, 618
        }
    }
}
